# For 
- architecture: inception_v3
  download_url: http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
  graph_definition_path: classify_image_graph_def.pb
  image_depth: 3
  image_input_size:
  - 299
  - 299
  input_node_name: Mul:0
  output_node_name: pool_3/_reshape:0
  output_tensor_size: 2048
  supports_batching: false
- architecture: mobilenet_v1_1.0_224_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224_quant.tgz
  graph_definition_path: mobilenet_v1_1.0_224_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 224
  - 224
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_1.0_224
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz
  graph_definition_path: mobilenet_v1_1.0_224_froze.pb
  image_depth: 3
  image_input_size:
  - 224
  - 224
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_1.0_192_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_192_quant.tgz
  graph_definition_path: mobilenet_v1_1.0_192_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 192
  - 192
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_1.0_192
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_192.tgz
  graph_definition_path: mobilenet_v1_1.0_192_froze.pb
  image_depth: 3
  image_input_size:
  - 192
  - 192
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_1.0_160_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_160_quant.tgz
  graph_definition_path: mobilenet_v1_1.0_160_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 160
  - 160
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_1.0_160
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_160.tgz
  graph_definition_path: mobilenet_v1_1.0_160_froze.pb
  image_depth: 3
  image_input_size:
  - 160
  - 160
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_1.0_128_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_128_quant.tgz
  graph_definition_path: mobilenet_v1_1.0_128_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 128
  - 128
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_1.0_128
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_128.tgz
  graph_definition_path: mobilenet_v1_1.0_128_froze.pb
  image_depth: 3
  image_input_size:
  - 128
  - 128
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.75_224_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.75_224_quant.tgz
  graph_definition_path: mobilenet_v1_0.75_224_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 224
  - 224
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.75_224
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.75_224.tgz
  graph_definition_path: mobilenet_v1_0.75_224_froze.pb
  image_depth: 3
  image_input_size:
  - 224
  - 224
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.75_192_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.75_192_quant.tgz
  graph_definition_path: mobilenet_v1_0.75_192_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 192
  - 192
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.75_192
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.75_192.tgz
  graph_definition_path: mobilenet_v1_0.75_192_froze.pb
  image_depth: 3
  image_input_size:
  - 192
  - 192
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.75_160_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.75_160_quant.tgz
  graph_definition_path: mobilenet_v1_0.75_160_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 160
  - 160
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.75_160
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.75_160.tgz
  graph_definition_path: mobilenet_v1_0.75_160_froze.pb
  image_depth: 3
  image_input_size:
  - 160
  - 160
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.75_128_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.75_128_quant.tgz
  graph_definition_path: mobilenet_v1_0.75_128_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 128
  - 128
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.75_128
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.75_128.tgz
  graph_definition_path: mobilenet_v1_0.75_128_froze.pb
  image_depth: 3
  image_input_size:
  - 128
  - 128
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.5_224_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.5_224_quant.tgz
  graph_definition_path: mobilenet_v1_0.5_224_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 224
  - 224
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.5_224
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.5_224.tgz
  graph_definition_path: mobilenet_v1_0.5_224_froze.pb
  image_depth: 3
  image_input_size:
  - 224
  - 224
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.5_192_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.5_192_quant.tgz
  graph_definition_path: mobilenet_v1_0.5_192_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 192
  - 192
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.5_192
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.5_192.tgz
  graph_definition_path: mobilenet_v1_0.5_192_froze.pb
  image_depth: 3
  image_input_size:
  - 192
  - 192
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.5_160_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.5_160_quant.tgz
  graph_definition_path: mobilenet_v1_0.5_160_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 160
  - 160
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.5_160
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.5_160.tgz
  graph_definition_path: mobilenet_v1_0.5_160_froze.pb
  image_depth: 3
  image_input_size:
  - 160
  - 160
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.5_128_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.5_128_quant.tgz
  graph_definition_path: mobilenet_v1_0.5_128_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 128
  - 128
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.5_128
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.5_128.tgz
  graph_definition_path: mobilenet_v1_0.5_128_froze.pb
  image_depth: 3
  image_input_size:
  - 128
  - 128
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.25_224_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.25_224_quant.tgz
  graph_definition_path: mobilenet_v1_0.25_224_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 224
  - 224
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.25_224
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.25_224.tgz
  graph_definition_path: mobilenet_v1_0.25_224_froze.pb
  image_depth: 3
  image_input_size:
  - 224
  - 224
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.25_192_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.25_192_quant.tgz
  graph_definition_path: mobilenet_v1_0.25_192_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 192
  - 192
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.25_192
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.25_192.tgz
  graph_definition_path: mobilenet_v1_0.25_192_froze.pb
  image_depth: 3
  image_input_size:
  - 192
  - 192
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.25_160_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.25_160_quant.tgz
  graph_definition_path: mobilenet_v1_0.25_160_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 160
  - 160
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.25_160
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.25_160.tgz
  graph_definition_path: mobilenet_v1_0.25_160_froze.pb
  image_depth: 3
  image_input_size:
  - 160
  - 160
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.25_128_quant
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.25_128_quant.tgz
  graph_definition_path: mobilenet_v1_0.25_128_quant_froze.pb
  image_depth: 3
  image_input_size:
  - 128
  - 128
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
- architecture: mobilenet_v1_0.25_128
  download_url: http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.25_128.tgz
  graph_definition_path: mobilenet_v1_0.25_128_froze.pb
  image_depth: 3
  image_input_size:
  - 128
  - 128
  input_node_name: input:0
  output_node_name: MobilenetV1/Predictions/Reshape:0
  output_tensor_size: 1001
  supports_batching: true
